---
title: "Simplification Logic to Build a Recommender System for ABIDE Dataset"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Simplification Logic to Build a Recommender System for ABIDE Dataset}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(fcaR)
library(tidyverse)
```

# Data

```{r}
base_folder <- file.path(normalizePath("~"),
                         "Documents",
                         "Research", "Congresos",
                         "2019", "CMMSE 2019",
                         "dataset_ABIDE")

my_data <- read.csv(file = file.path(base_folder, "data.csv"))

my_data$SUBJ_ID <- NULL
my_data$X       <- NULL
```

## Preprocessing

```{r}
scale_values <- function(v, upper = FALSE, intervals = 2) {
  
  v_ <- mean(v)
  vsd <- sd(v)

  v2 <- (v - v_) / vsd
  v2[!is.finite(v2)] <- 0
  res <- 1 - pnorm(v2)
  res[res <= 0.5] <- 0
  
  # Saturate
  res[res >= 0.9] <- 1

  res[res > 0.5] <- (res[res > 0.5] - 0.5) * 2
  
  floor(res * intervals) / intervals
  
}

n_breaks <- 4

scaled_data <- sapply(data.frame(my_data), function(s) scale_values(s, intervals = n_breaks))

colnames(scaled_data) <- colnames(my_data)
scaled_data[, "group"] <- as.numeric(my_data$group)

thk_vars <- ends_with(vars = colnames(scaled_data), 
                      match = "thickness")

scaled2 <- scaled_data[, -thk_vars]
```

# Implications

```{r}
fc <- formal_context$new(scaled2)
fc$extract_implications_concepts(verbose = FALSE)

fc$implications$cardinality()
sizes <- fc$implications$size()
colMeans(sizes)
```

# Reduction of the Ruleset

```{r}
fc$implications$batch_apply(rules = c("composition",
                                      "generalization",
                                      "simplification"))

fc$implications$cardinality()
sizes <- fc$implications$size()
colMeans(sizes)
```

# Filtering the Ruleset

```{r}
fc$implications$filter_by_rhs(attr_filter = "group")
```

# Closure of the Diagnostic Attribute

```{r}
S <- build_set(attrs = "group", values = 1, fc$attributes)

cl <- fc$implications$compute_closure(S)
print_set(cl, fc$attributes)
```

