# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

which_at_col_C <- function(x_i, x_p, col) {
    .Call(`_fcaR_which_at_col_C`, x_i, x_p, col)
}

pre_condition <- function(x_i, y_i) {
    .Call(`_fcaR_pre_condition`, x_i, y_i)
}

is_pre_condition <- function(x_i, x_p, y_i, y_p) {
    .Call(`_fcaR_is_pre_condition`, x_i, x_p, y_i, y_p)
}

is_subset_individual <- function(x_i, x, y_i, y, len) {
    .Call(`_fcaR_is_subset_individual`, x_i, x, y_i, y, len)
}

compare_elements_first <- function(x) {
    .Call(`_fcaR_compare_elements_first`, x)
}

compare_elements_other <- function(x, idx_i, idx_j) {
    .Call(`_fcaR_compare_elements_other`, x, idx_i, idx_j)
}

compare_equality_other <- function(x, idx_i, idx_j) {
    .Call(`_fcaR_compare_equality_other`, x, idx_i, idx_j)
}

flatten_sparse_C <- function(p, i, x, dims) {
    .Call(`_fcaR_flatten_sparse_C`, p, i, x, dims)
}

intent_C <- function(A, I) {
    .Call(`_fcaR_intent_C`, A, I)
}

extent_C <- function(A, I) {
    .Call(`_fcaR_extent_C`, A, I)
}

closure_C <- function(A, I) {
    .Call(`_fcaR_closure_C`, A, I)
}

ganters_algorithm <- function(I, grades_set, n_attributes) {
    .Call(`_fcaR_ganters_algorithm`, I, grades_set, n_attributes)
}

self_intersection_C <- function(x_i, x_p, y_i, y_p) {
    .Call(`_fcaR_self_intersection_C`, x_i, x_p, y_i, y_p)
}

is_subset_C <- function(X_P, X_I, X_DIM, X, Y_P, Y_I, Y_DIM, Y, PROPER, OUT_P) {
    .Call(`_fcaR_is_subset_C`, X_P, X_I, X_DIM, X, Y_P, Y_I, Y_DIM, Y, PROPER, OUT_P)
}

intersects_C <- function(X_P, X_I, X_DIM, Y_P, Y_I, Y_DIM, OUT_P) {
    .Call(`_fcaR_intersects_C`, X_P, X_I, X_DIM, Y_P, Y_I, Y_DIM, OUT_P)
}

is_equal_set_C <- function(X_P, X_I, X_DIM, X, Y_P, Y_I, Y_DIM, Y, PROPER, OUT_P) {
    .Call(`_fcaR_is_equal_set_C`, X_P, X_I, X_DIM, X, Y_P, Y_I, Y_DIM, Y, PROPER, OUT_P)
}

is_subset_binary <- function(X_P, X_I, X_DIM, Y_P, Y_I, Y_DIM, PROPER, OUT_P) {
    .Call(`_fcaR_is_subset_binary`, X_P, X_I, X_DIM, Y_P, Y_I, Y_DIM, PROPER, OUT_P)
}

apply_F_colwise <- function(x, type, init_value) {
    .Call(`_fcaR_apply_F_colwise`, x, type, init_value)
}

apply_F_rowwise <- function(x, type, init_value) {
    .Call(`_fcaR_apply_F_rowwise`, x, type, init_value)
}

apply_F_rowwise_xy <- function(x, y, type) {
    .Call(`_fcaR_apply_F_rowwise_xy`, x, y, type)
}

apply_F_elementwise <- function(x, y, type) {
    .Call(`_fcaR_apply_F_elementwise`, x, y, type)
}

