# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

tnorm_Zadeh <- function(x, y) {
    .Call(`_fcaR_tnorm_Zadeh`, x, y)
}

implication_Zadeh <- function(x, y) {
    .Call(`_fcaR_implication_Zadeh`, x, y)
}

tnorm_Lukasiewicz <- function(x, y) {
    .Call(`_fcaR_tnorm_Lukasiewicz`, x, y)
}

implication_Lukasiewicz <- function(x, y) {
    .Call(`_fcaR_implication_Lukasiewicz`, x, y)
}

tnorm_Godel <- function(x, y) {
    .Call(`_fcaR_tnorm_Godel`, x, y)
}

implication_Godel <- function(x, y) {
    .Call(`_fcaR_implication_Godel`, x, y)
}

tnorm_Product <- function(x, y) {
    .Call(`_fcaR_tnorm_Product`, x, y)
}

implication_Product <- function(x, y) {
    .Call(`_fcaR_implication_Product`, x, y)
}

available_logics <- function() {
    .Call(`_fcaR_available_logics`)
}

print_matrix <- function(I) {
    invisible(.Call(`_fcaR_print_matrix`, I))
}

print_vector <- function(I, sz) {
    invisible(.Call(`_fcaR_print_vector`, I, sz))
}

get_element_array <- function(I, i, j, k) {
    .Call(`_fcaR_get_element_array`, I, i, j, k)
}

next_closure_implications <- function(I, grades_set, attrs, connection = "standard", name = "Zadeh", save_concepts = TRUE, verbose = FALSE) {
    .Call(`_fcaR_next_closure_implications`, I, grades_set, attrs, connection, name, save_concepts, verbose)
}

next_closure_concepts <- function(I, grades_set, attrs, connection = "standard", name = "Zadeh", verbose = FALSE, ret = TRUE) {
    .Call(`_fcaR_next_closure_concepts`, I, grades_set, attrs, connection, name, verbose, ret)
}

compute_upright_arrow <- function(V, I, name) {
    .Call(`_fcaR_compute_upright_arrow`, V, I, name)
}

compute_downleft_arrow <- function(V, I, name) {
    .Call(`_fcaR_compute_downleft_arrow`, V, I, name)
}

compute_upleft_arrow <- function(V, I, name) {
    .Call(`_fcaR_compute_upleft_arrow`, V, I, name)
}

compute_downright_arrow <- function(V, I, name) {
    .Call(`_fcaR_compute_downright_arrow`, V, I, name)
}

compute_intent <- function(V, I, connection, name) {
    .Call(`_fcaR_compute_intent`, V, I, connection, name)
}

compute_extent <- function(V, I, connection, name) {
    .Call(`_fcaR_compute_extent`, V, I, connection, name)
}

compute_closure <- function(V, I, connection, name) {
    .Call(`_fcaR_compute_closure`, V, I, connection, name)
}

self_intersection_C <- function(x_i, x_p, y_i, y_p) {
    .Call(`_fcaR_self_intersection_C`, x_i, x_p, y_i, y_p)
}

is_subset_C <- function(X_P, X_I, X_DIM, X, Y_P, Y_I, Y_DIM, Y, PROPER, OUT_P) {
    .Call(`_fcaR_is_subset_C`, X_P, X_I, X_DIM, X, Y_P, Y_I, Y_DIM, Y, PROPER, OUT_P)
}

intersects_C <- function(X_P, X_I, X_DIM, Y_P, Y_I, Y_DIM, OUT_P) {
    .Call(`_fcaR_intersects_C`, X_P, X_I, X_DIM, Y_P, Y_I, Y_DIM, OUT_P)
}

is_equal_set_C <- function(X_P, X_I, X_DIM, X, Y_P, Y_I, Y_DIM, Y, PROPER, OUT_P) {
    .Call(`_fcaR_is_equal_set_C`, X_P, X_I, X_DIM, X, Y_P, Y_I, Y_DIM, Y, PROPER, OUT_P)
}

which_at_col <- function(x_i, x_p, col) {
    .Call(`_fcaR_which_at_col`, x_i, x_p, col)
}

flatten_sparse_C <- function(p, i, x, dims) {
    .Call(`_fcaR_flatten_sparse_C`, p, i, x, dims)
}

set_difference <- function(xi, xp, xx, yi, yp, yx, number) {
    .Call(`_fcaR_set_difference`, xi, xp, xx, yi, yp, yx, number)
}

set_difference_single <- function(xi, xp, xx, yi, yp, yx, number) {
    .Call(`_fcaR_set_difference_single`, xi, xp, xx, yi, yp, yx, number)
}

set_intersection_single <- function(xi, xp, xx, yi, yp, yx, number) {
    .Call(`_fcaR_set_intersection_single`, xi, xp, xx, yi, yp, yx, number)
}

